# Generated by Django 5.1.7 on 2025-04-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_alter_farmer_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='farmers/'),
        ),
    ]
